---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.KubiyaNatsJwtSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.nats }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.OpenFaasSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.openfaas }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}